In [1]:
print('Hello World')

Hello World


In [2]:
def even_or_odd(num):
    if num%2 == 0:
        print('even')
    else:
        print('odd')

In [3]:
even_or_odd(13)

odd


In [4]:
even_or_odd(86)

even


In [5]:
print(22/2)

11.0


In [6]:
print(5.0 * 8)

40.0


In [7]:
print('-----o-----')
print('-----------')
print('\n')
print('-----\/----')

-----o-----
-----------


-----\/----


In [8]:
import numpy as np

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.random.randint(10)

4

In [17]:
np.linspace(10, 15)

array([10.        , 10.10204082, 10.20408163, 10.30612245, 10.40816327,
       10.51020408, 10.6122449 , 10.71428571, 10.81632653, 10.91836735,
       11.02040816, 11.12244898, 11.2244898 , 11.32653061, 11.42857143,
       11.53061224, 11.63265306, 11.73469388, 11.83673469, 11.93877551,
       12.04081633, 12.14285714, 12.24489796, 12.34693878, 12.44897959,
       12.55102041, 12.65306122, 12.75510204, 12.85714286, 12.95918367,
       13.06122449, 13.16326531, 13.26530612, 13.36734694, 13.46938776,
       13.57142857, 13.67346939, 13.7755102 , 13.87755102, 13.97959184,
       14.08163265, 14.18367347, 14.28571429, 14.3877551 , 14.48979592,
       14.59183673, 14.69387755, 14.79591837, 14.89795918, 15.        ])